[theme]
#primaryColor="#F63366"
primaryColor = "#1B9E3A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
fileWatcherType = "poll"

[ui]
hideTopBar = true
